### ISSUE TITLE
Add folia support

### ISSUE THREAD

**Issue by Xemorr** [lichenaut/DatapackLoader#9]
I wanted to use this as datapacks are one of the only ways in Folia to load custom worlds - this plugin would be especially useful on Folia.

**Comment by lichenaut** [comment]
Hey, I don't see why DatapackLoader wouldn't work on Folia, as I've tested it on Paper forks before, and I don't see how region-based ticking is related to the way DatapackLoader works, but then again I'm not too familiar with Folia. Have you tested it on Folia and it didn't work? Is there something you think I'm not seeing?

**Comment by Xemorr** [comment]
> Hey, I don't see why DatapackLoader wouldn't work on Folia, as I've tested it on Paper forks before, and I don't see how region-based ticking is related to the way DatapackLoader works, but then again I'm not too familiar with Folia. Have you tested it on Folia and it didn't work? Is there something you think I'm not seeing?

You need to add folia-supported: true to the plugin if you believe it is folia compatible, otherwise it won't load

**Comment by lichenaut** [comment]
Ah, I see. I've added the new version that supports Folia to this repo, SpigotMC, and Modrinth.

**Comment by kevinsnijder** [comment]
This does not work (anymore?). I tried this since Folia does not support loading datapacks at all.
Even with this, folia does not like datapacks being loaded and throws a big load of errors.
I removed all datapacks from my world folder and moved them into the plugins world folder.
It threw some errors at extracting the datapack zip files, so I also did that myself.
The server starts up, throws a ton of errors and then just works without datapacks.

[latest.log](https://github.com/user-attachments/files/18675685/latest.log)

**Comment by lichenaut** [comment]
Hey, sorry for the late reply. You're right, just because DatapackLoader "feeds" datapacks into the Folia server, it does not mean the Folia server will correctly handle such datapacks. Making all datapacks run on Folia is not a feature of DatapackLoader. Rather, DatapackLoader being Folia-compatible is for the user who wants to load already Folia-compatible datapacks. I'm open to looking at the extraction-related errors.

**Comment by kevinsnijder** [comment]
@lichenaut Folia compatible datapacks? Do you have examples of those?
I'm pretty sure folia doesn't support any type of datapacks, I feel like marking it compatible with folia is very misleading.

**Comment by lichenaut** [comment]
Maybe datapacks that strictly focus on custom recipes, advancements, or loot tables would work? Folia disables the `datapack` command, and I couldn't find any examples, which at the least implies it's risky. However, making the change seemed valuable to someone, and I figured it wouldn't hurt to add it. I'll add a note that the plugin doesn't make datapacks compatible with Folia.
